[processing]
parallel_processing = true
chunk_size = 100
max_concurrent_files = 1000
file_size_limit_mb = 10
timeout_seconds = 30

[cache]
enable_persistent_cache = true
enable_memory_cache = true
cache_dir = "/var/folders/c2/j7cjsscs213f3j7_qtqddw5r0000gn/T/lsp-bridge-cache"
max_size_mb = 100
max_entries = 10000
ttl_hours = 24
cleanup_interval_minutes = 60

[memory]
max_memory_mb = 256
max_entries = 50000
eviction_policy = "Adaptive"
high_water_mark = 0.8
low_water_mark = 0.6
eviction_batch_size = 100
monitoring_interval_seconds = 30

[error_recovery]
enable_circuit_breaker = true
max_retries = 3
initial_delay_ms = 100
max_delay_ms = 5000
backoff_multiplier = 2.0
failure_threshold = 5
success_threshold = 3
timeout_ms = 10000

[git]
enable_git_integration = true
scan_interval_seconds = 30
ignore_untracked = false
track_staged_changes = true
auto_refresh = true

[metrics]
enable_metrics = true
prometheus_port = 9090
collection_interval_seconds = 10
retention_hours = 72
export_format = "prometheus"

[features]
auto_optimization = true
health_monitoring = true
cache_warming = true
advanced_diagnostics = false
experimental_features = false

[performance]
optimization_interval_minutes = 60
health_check_interval_minutes = 5
gc_threshold_mb = 512
max_cpu_usage_percent = 80.0
adaptive_scaling = true
