# LSP Bridge Configuration
# This file configures the behavior of the LSP Bridge service

[processing]
parallel_processing = true
chunk_size = 500  # Increased for better throughput
max_concurrent_files = 200  # Reduced to prevent resource exhaustion
file_size_limit_mb = 10
timeout_seconds = 30

[cache]
enable_persistent_cache = true
enable_memory_cache = true
# cache_dir is automatically determined based on platform
# Use LSP_BRIDGE_CACHE_DIR environment variable to override
max_size_mb = 500  # Increased for better hit rates
max_entries = 10000
ttl_hours = 24
cleanup_interval_minutes = 60
compression_enabled = true  # New: compress cached data
cache_tiers = ["hot", "warm", "cold"]  # New: tiered caching

[memory]
max_memory_mb = 512  # Increased for better performance
max_entries = 50000
eviction_policy = "Adaptive"
high_water_mark = 0.8
low_water_mark = 0.6
eviction_batch_size = 100
monitoring_interval_seconds = 30
memory_pressure_detection = true  # New: detect system memory pressure

[error_recovery]
enable_circuit_breaker = true
max_retries = 3
initial_delay_ms = 100
max_delay_ms = 5000
backoff_multiplier = 2.0
failure_threshold = 5
success_threshold = 3
timeout_ms = 10000
retry_jitter = true  # New: add jitter to prevent thundering herd
error_categorization = true  # New: handle different error types

[git]
enable_git_integration = true
scan_interval_seconds = 90  # Increased to reduce overhead
ignore_untracked = false
track_staged_changes = true
auto_refresh = true
respect_gitignore = true  # New: honor .gitignore patterns
branch_aware_caching = true  # New: cache per branch

[metrics]
enable_metrics = true
prometheus_port = 9090
collection_interval_seconds = 30  # Reduced frequency
retention_hours = 72
export_format = "prometheus"
enable_opentelemetry = true  # New: distributed tracing
custom_metrics = ["cache_hit_rate", "processing_time_by_type"]  # New

[features]
auto_optimization = true
health_monitoring = true
cache_warming = true
advanced_diagnostics = false
experimental_features = false

[performance]
optimization_interval_minutes = 60
health_check_interval_minutes = 5
gc_threshold_mb = 512
max_cpu_usage_percent = 80.0
adaptive_scaling = true

# Language-specific settings
[languages.rust]
max_file_size_mb = 20
parallel_analysis = true
incremental_parsing = true

[languages.typescript]
max_file_size_mb = 15
parallel_analysis = true
use_incremental_parsing = true

[languages.go]
max_file_size_mb = 20
parallel_analysis = true

[languages.python]
max_file_size_mb = 10
parallel_analysis = true

# Security settings
[security]
max_file_path_length = 4096
disallow_symlinks_outside_workspace = true
scan_for_secrets = true
allowed_file_extensions = ["rs", "ts", "js", "go", "py", "java", "cpp", "c", "h", "hpp"]

# Profile configurations
[profiles.development]
debug_logging = true
aggressive_caching = false
detailed_error_messages = true
performance_profiling = true

[profiles.production]
debug_logging = false
aggressive_caching = true
detailed_error_messages = false
performance_profiling = false

[profiles.testing]
debug_logging = true
aggressive_caching = false
mock_external_services = true
deterministic_ids = true

# Network settings (for future distributed mode)
[network]
connection_pool_size = 10
request_timeout_seconds = 30
enable_http2 = true
max_retries = 3
keepalive_seconds = 60